services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "3082:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchises-app
    ports:
      - "3081:3081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:3082/franchisesdb
    depends_on:
      - mongodb

volumes:
  mongodb_data: