name: ❓ Question
description: Ask a question about the project
title: "[QUESTION]: "
labels: ["question", "needs-triage"]
assignees: ["carrilloapps"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! 🤔
        
        Please provide as much context as possible to help us give you the best answer.

  - type: textarea
    id: question
    attributes:
      label: ❓ Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: dropdown
    id: question-category
    attributes:
      label: 🏷️ Question Category
      description: What category does your question fall into?
      options:
        - API Usage
        - Configuration
        - Deployment
        - Database
        - Authentication
        - Performance
        - Best Practices
        - Troubleshooting
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🔍 Context
      description: Provide any relevant context about your situation
      placeholder: |
        - What are you trying to achieve?
        - What have you already tried?
        - Any specific constraints or requirements?
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: 💻 Code Example (if applicable)
      description: Share any relevant code snippets
      placeholder: |
        ```kotlin
        // Your code here
        ```
        
        or
        
        ```bash
        # Commands you're running
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 🌐 Environment Details
      description: Provide details about your environment if relevant
      placeholder: |
        - OS: [e.g. Windows 11, Ubuntu 22.04]
        - Java Version: [e.g. 17]
        - Spring Boot Version: [e.g. 3.5.0]
        - MongoDB Version: [e.g. 7.0]
        - Docker Version: [e.g. 24.0.5] (if applicable)
    validations:
      required: false

  - type: textarea
    id: expected-outcome
    attributes:
      label: 🎯 Expected Outcome
      description: What outcome are you hoping to achieve?
      placeholder: Describe what you're trying to accomplish or what result you expect
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: 📝 Additional Information
      description: Any other information that might be helpful
      placeholder: Links to documentation you've read, error messages, screenshots, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 📋 Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation
          required: true
        - label: I have provided sufficient context for my question
          required: true