package app.carrillo.franchises.domain

import org.bson.types.ObjectId
import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document

/**
 * Data class representing a Franchise.
 *
 * @property id The unique identifier of the franchise. Automatically generated by MongoDB.
 * @property name The name of the franchise.
 * @property branches A list of branches belonging to this franchise.
 */
@Document(collection = "franchises")
data class Franchise(
    @Id
    val id: String = ObjectId.get().toHexString(),
    val name: String,
    val address: String? = null,
    val description: String? = null,
    val branches: List<Branch> = emptyList()
)

/**
 * Data class representing a Branch within a Franchise.
 *
 * @property name The name of the branch.
 * @property products A list of products offered in this branch.
 */
data class Branch(
    val name: String,
    val products: List<Product> = emptyList()
)

/**
 * Data class representing a Product offered in a Branch.
 *
 * @property name The name of the product.
 * @property stock The quantity of the product in stock.
 */
data class Product(
    val name: String,
    val stock: Int,
    val price: Double? = null
)